# Generated by Django 4.2 on 2023-04-29 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SalaryInput', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='salary',
            name='description',
            field=models.CharField(blank=True, max_length=3000),
        ),
        migrations.AddField(
            model_name='salary',
            name='pay_status',
            field=models.CharField(default='N', max_length=1),
            preserve_default=False,
        ),
    ]
