# Generated by Django 4.2 on 2023-04-29 20:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SalaryInput', '0002_salary_description_salary_pay_status'),
    ]

    operations = [
        migrations.RenameField(
            model_name='employee',
            old_name='ChiName',
            new_name='chi_name',
        ),
        migrations.RenameField(
            model_name='employee',
            old_name='EngName',
            new_name='eng_name',
        ),
        migrations.AlterField(
            model_name='salary',
            name='id',
            field=models.CharField(default='', editable=False, max_length=7, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='salary',
            name='month',
            field=models.CharField(max_length=2),
        ),
    ]
