# Generated by Django 4.2 on 2023-05-01 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SalaryInput', '0004_class_alter_employee_options_rename_pid_salary_pid'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='classes',
            field=models.ManyToManyField(default=None, to='SalaryInput.class'),
        ),
    ]
