version: '3.8'

services:
  django_gunicorn:
    volumes:
      - static:/static
    env_file:
      - .env
    build:
      context: .
    ports:
      - "8098:8098"
  nginx:
    build:
      ./nginx
    volumes:
      - static:/static
    ports:
      - "8099:8099"
    depends_on:
      - django_gunicorn
    


volumes:
  static: