# Generated by Django 4.2 on 2023-04-30 05:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('SalaryInput', '0002_alter_salary_month'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='salary',
            options={'ordering': ['month']},
        ),
    ]
