# Generated by Django 4.2 on 2023-05-01 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SalaryInput', '0003_alter_salary_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='Class',
            fields=[
                ('CID', models.CharField(default='', editable=False, max_length=20, primary_key=True, serialize=False)),
                ('intrument', models.CharField(max_length=20)),
                ('duration', models.IntegerField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=6)),
            ],
        ),
        migrations.AlterModelOptions(
            name='employee',
            options={'ordering': ['SID', 'chi_name']},
        ),
        migrations.RenameField(
            model_name='salary',
            old_name='pid',
            new_name='PID',
        ),
    ]
