# Generated by Django 4.2 on 2023-05-02 15:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('SalaryInput', '0008_alter_class_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='class',
            options={'ordering': ['CID', 'type', 'level']},
        ),
        migrations.RenameField(
            model_name='class',
            old_name='grade',
            new_name='level',
        ),
        migrations.RenameField(
            model_name='class',
            old_name='instrument',
            new_name='type',
        ),
    ]
