# Generated by Django 4.2 on 2023-05-02 16:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('SalaryInput', '0009_alter_class_options_rename_grade_class_level_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='class',
            options={'ordering': ['type', 'level', 'duration']},
        ),
    ]
