# Generated by Django 4.2 on 2023-05-06 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SalaryInput', '0011_alter_class_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salary',
            name='PID',
            field=models.CharField(default='', editable=False, max_length=11, primary_key=True, serialize=False),
        ),
    ]
