# Generated by Django 4.2 on 2023-05-06 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SalaryInput', '0012_alter_salary_pid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='classes',
            field=models.ManyToManyField(blank=True, default=None, to='SalaryInput.class'),
        ),
    ]
