# Generated by Django 4.2 on 2023-05-07 11:41

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('SalaryInput', '0013_alter_employee_classes'),
    ]

    operations = [
        migrations.AddField(
            model_name='salary',
            name='cheque_id',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AddField(
            model_name='salary',
            name='created_time',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='salary',
            name='paid_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
