# Generated by Django 4.2 on 2023-06-06 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SalaryInput', '0015_rename_cheque_id_salary_cheque_number_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salary',
            name='cheque_number',
            field=models.CharField(blank=True, max_length=12),
        ),
    ]
