# Generated by Django 4.2 on 2024-08-10 22:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SalaryInput', '0016_alter_salary_cheque_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='hourly_rate',
            field=models.TextField(blank=True, null=True),
        ),
    ]
