# Generated by Django 4.2 on 2023-04-30 05:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('SID', models.IntegerField(primary_key=True, serialize=False)),
                ('chi_name', models.CharField(blank=True, max_length=8)),
                ('eng_name', models.CharField(blank=True, max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Salary',
            fields=[
                ('month', models.CharField(max_length=2)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('description', models.CharField(blank=True, max_length=3000)),
                ('pay_status', models.CharField(max_length=10)),
                ('pid', models.CharField(default='', editable=False, max_length=7, primary_key=True, serialize=False)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SalaryInput.employee')),
            ],
        ),
    ]
